### ISSUE TITLE
Error program run

### ISSUE THREAD

**Issue by criss20ster** [caheuer/tso-collectible-finder#1]
I have a trouble tso client finder coletiable 

https://i.imgur.com/vvqagQc.png

**Comment by caheuer** [comment]
Hello @criss20ster!

Thank you for opening this issue.

It seems like there was an incompatibility issue with Windows 7. I have rebuilt the application using Python 3.8 instead of Python 3.9, and it works on my test machine now.

Please download the latest version (https://github.com/caheuer/tso-collectible-finder/releases/tag/v1.0.1) and try it out.

Let me know if that fixed the problem for you.

Cheers,
caheuer

**Comment by criss20ster** [comment]
Ok thx it's good. Works ideal
