### ISSUE TITLE
Why is the virus detected?

### ISSUE THREAD

**Issue by reibabo** [caheuer/tso-collectible-finder#2]
![Screenshot_6](https://user-images.githubusercontent.com/80452523/110761301-eb553c80-8292-11eb-92db-d7612404ed52.jpg)

Virus is detected.
Is this a safe file? Why is it recognized as a virus?

**Comment by caheuer** [comment]
Hi reibabo,

The file is probably flagged as a virus by some virus scanners due to it editing the Windows hosts file to reroute the requests to the Ubisoft servers. You can check out what exactly my program does by checking out the Python source file. The .exe I uploaded was made using PyInstaller on the script. You can also directly execute the Python script if you have Python installed on your computer (you must do this with administrative privileges then due to the editing of the Windows hosts file).

Cheers

**Comment by reibabo** [comment]
Thanks for explaining.
If I close the program, will the host file be restored to the original?
